apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytheatre-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mytheatre
  template:
    metadata:
      labels:
        app: mytheatre
    spec:
      containers:
      - name: mytheatre
        image: ghcr.io/your-username/mytheatre:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi" 